# Generated by Django 3.0.4 on 2020-03-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('pno', models.CharField(max_length=13)),
                ('query', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='course_assign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=20)),
                ('course_company', models.CharField(max_length=20)),
                ('assignment', models.CharField(max_length=5000)),
                ('remark', models.CharField(max_length=2500)),
            ],
        ),
        migrations.CreateModel(
            name='course_pro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=20)),
                ('course_company', models.CharField(max_length=20)),
                ('projects', models.CharField(max_length=5000)),
                ('remark', models.CharField(max_length=2500)),
            ],
        ),
        migrations.CreateModel(
            name='enquiry_model',
            fields=[
                ('brand', models.CharField(max_length=20)),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('mobile', models.CharField(max_length=13)),
                ('tele', models.CharField(max_length=10)),
                ('source', models.CharField(max_length=20)),
                ('campaign', models.CharField(max_length=25)),
                ('comments', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('eduqual', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=15)),
                ('pin', models.CharField(max_length=15)),
                ('gname', models.CharField(max_length=20)),
                ('gaddress', models.CharField(max_length=150)),
                ('gmobile', models.CharField(max_length=13)),
                ('gtele', models.CharField(max_length=10)),
                ('fathname', models.CharField(max_length=50)),
                ('mothname', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('subpos', models.CharField(max_length=10)),
                ('sts1', models.CharField(max_length=100)),
                ('sts2', models.CharField(max_length=100)),
                ('sts3', models.CharField(max_length=100)),
            ],
        ),
    ]
