# Generated by Django 3.0.4 on 2020-03-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OptionsTechnikaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='register_model',
            fields=[
                ('fullname', models.CharField(max_length=60)),
                ('username', models.CharField(max_length=30)),
                ('pro_pic', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('pno', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('pass1', models.CharField(max_length=50)),
                ('pass2', models.CharField(max_length=50)),
                ('inst_name_10', models.CharField(max_length=50)),
                ('cgpa_10', models.IntegerField()),
                ('board_10', models.CharField(max_length=40)),
                ('major_10', models.CharField(max_length=20)),
                ('start_date_10', models.DateField()),
                ('end_date_10', models.DateField()),
                ('inst_name_12', models.CharField(max_length=50)),
                ('cgpa_12', models.IntegerField()),
                ('board_12', models.CharField(max_length=40)),
                ('major_12', models.CharField(max_length=20)),
                ('start_date_12', models.DateField()),
                ('end_date_12', models.DateField()),
                ('inst_name_clg', models.CharField(max_length=50)),
                ('cgpa_clg', models.IntegerField()),
                ('uni_clg', models.CharField(max_length=50)),
                ('major_clg', models.CharField(max_length=20)),
                ('start_date_clg', models.DateField()),
                ('end_date_clg', models.DateField()),
                ('fath_name', models.CharField(max_length=50)),
                ('fath_age', models.IntegerField()),
                ('fath_occ', models.CharField(max_length=25)),
                ('fath_qua', models.CharField(max_length=20)),
                ('moth_name', models.CharField(max_length=50)),
                ('moth_age', models.IntegerField()),
                ('moth_occ', models.CharField(max_length=25)),
                ('moth_qua', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=30)),
            ],
        ),
    ]
