# Generated by Django 3.0.4 on 2020-03-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OptionsTechnikaApp', '0004_auto_20200311_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_model',
            name='pro_pic',
            field=models.ImageField(upload_to='images'),
        ),
    ]
