# Generated by Django 3.0.4 on 2020-03-11 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OptionsTechnikaApp', '0005_auto_20200312_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_model',
            name='pro_pic',
            field=models.ImageField(upload_to=''),
        ),
    ]
