# Generated by Django 3.0.4 on 2020-05-25 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OptionsTechnikaApp', '0006_auto_20200312_0005'),
    ]

    operations = [
        migrations.CreateModel(
            name='alumini_model',
            fields=[
                ('filepath', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=4)),
                ('salary', models.CharField(max_length=15)),
            ],
        ),
    ]
